name: CD

on:
  push:
    branches: [ main ]
  # schedule:
    #- cron: '0 0 * * *'

env:
  DBT_PROFILES_DIR: .
  # Removed BigQuery-specific environment variables

jobs:
  dbt-cd:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives write permission to the workflow
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-duckdb
    
    # Set MotherDuck token as environment variable
    - name: Set MotherDuck token
      run: |
        echo "MOTHERDUCK_TOKEN=${{ secrets.MOTHERDUCK_TOKEN }}" >> $GITHUB_ENV
    
    - name: Run dbt commands
      run: |
        dbt deps --profiles-dir . --project-dir .
        dbt build --profiles-dir . --project-dir . --target prod
    
    - name: Update prod manifest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dbt compile --profiles-dir . --project-dir . --target prod --target-path=prod-run-artifacts
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add prod-run-artifacts/manifest.json
        git commit -m "Update prod manifest" || echo "No changes to commit"
        git push
