name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: .
  # Removed BigQuery-specific environment variables

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install dbt-duckdb
    
    # Set MotherDuck token as environment variable
    - name: Set MotherDuck token
      run: |
        echo "MOTHERDUCK_TOKEN=${{ secrets.MOTHERDUCK_TOKEN }}" >> $GITHUB_ENV
    
    - name: Install dbt dependencies
      run: dbt deps
    
    - name: Checkout doc branch
      run: |
        git checkout -B gh-pages
    
    - name: Generate dbt docs
      run: dbt docs generate -t prod
    
    - name: Move files to doc directory
      run: |
        mkdir -p ./docs
        cp target/{catalog.json,manifest.json,index.html} docs/
    
    - name: Clean up target directory
      run: dbt clean
    
    - name: Check for changes
      run: git status
    
    - name: Stage changed files
      run: git add .
    
    - name: Commit changes
      run: |
        git config user.email "abc@xyz.com"
        git config user.name "github-actions"
        git commit -am "Auto-update docs"
    
    - name: Push changes to doc 
      run: |
        git push -f --set-upstream origin gh-pages